### ISSUE TITLE
Add species names to diet estimates that are returned in p.QFASA

### ISSUE THREAD

**Issue by cstewartGH** [justinkamerman/QFASA#10]

**Comment by Gary3321** [comment]
fixed

**Comment by justinkamerman** [comment]
Is there a pull request for this fix @hongchangbao ?

**Comment by Gary3321** [comment]
Hi Justin,


I created the pull request just now.


Thanks,


Hongchang

________________________________

**Comment by cstewartGH** [comment]
I created an issue for this and talked to Hongchang about it.  Is this what a pull request means?

Hard to explain over email but realized recently that it's actually quite important to have the species' names returned.


Sent from my Samsung Galaxy smartphone.


-------- Original message --------
